course_registration/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("courses.urls")),
]

courses/urls.py
# courses/urls.py

from django.urls import path
from . import views
from .views import save_selected_students

urlpatterns = [
    path('my_courses/', views.my_courses, name="my_courses"),
    path('homeAdmin/', views.homeAdmin, name="homeAdmin"),
    path('home/', views.home, name="home"),
    path('', views.login_view, name="login"),
    path('register/', views.register, name="register"),
    path('student_registration/', views.student_registration, name='student_registration'),
    path('register_course/<str:course_code>/', views.register_course, name="register_course"),
    path('profile/', views.profile, name="profile"),
    path('course_report/', views.course_report, name="course_report"),
    path('delete_course/<str:course_code>/', views.delete_course, name="delete_course"),
    path('addcourse/', views.add_course, name='add_course'),
    path('course_list/', views.course_lista, name='course_list'),
    path('addschedule/', views.add_schedule, name='add_schedule'),
    path('schedule_list/', views.schedule_list, name='schedule_list'),
    path('student_course_list/', views.student_course_list, name='student_course_list'),
    path('logout/', views.logout_view, name="logout"),
    path('courses/', views.courses, name="courses"),
    path('remove&editcourse/', views.removeeditcourse, name='removeeditcourse'),
    path('update_course/<str:course_code>/', views.update_course, name='update_course'),
    path('unregister/<str:course_code>/', views.unregister_course, name='unregister_course'),
    path('save_selected_students/', save_selected_students, name='save_selected_students'),
]

courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
class Student(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        indexes = [
            models.Index(fields=['user']),
        ]

    def __str__(self):
        return self.user.username

class CourseSchedule(models.Model):
    DAY_CHOICES = (
        ('S,T,T', 'Sunday, Tuesday, Thursday'),
        ('M,W', 'Monday, Wednesday'),
        ('S,T', 'Sunday, Tuesday'),
        ('S,T', 'Sunday, Thursday'),
        ('S', 'Sunday'),
        ('M', 'Monday'),
        ('T', 'Tuesday'),
        ('w', 'Wednesday'),
        ('T', 'Thursday'),
    )
    
    days = models.CharField(max_length=50, null=True, choices=DAY_CHOICES)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    room_no = models.CharField(max_length=10, null=True)

    def __str__(self):
        return f"{self.days} ({self.start_time} - {self.end_time})"

    def clean(self):
        if self.end_time <= self.start_time:
            raise ValidationError('End time must be after start time')

class Course(models.Model):
    code = models.CharField(max_length=90, unique=True, primary_key=True)
    name = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)
    instructor = models.CharField(max_length=100, null=True)
    scheduled = models.ForeignKey(CourseSchedule, on_delete=models.PROTECT, related_name='courses')
    prerequisites = models.ManyToManyField('self', blank=True, symmetrical=False)
    capacity = models.IntegerField(null=True)
    students = models.ManyToManyField(Student, related_name='courses',blank=True)

    class Meta:
        indexes = [
            models.Index(fields=['code']),
        ]

    def __str__(self):
        return self.name

    def clean(self):
        if self.capacity < 0:
            raise ValidationError('Capacity must be a positive number')

class StudentRegistrationManager(models.Manager):
    def create_registration(self, student, course):
        if StudentRegistration.objects.filter(student=student, course=course).exists():
            raise ValidationError('Student is already registered in this course')
        if course.prerequisites.exists() and not all(prerequisite in student.courses.all() for prerequisite in course.prerequisites.all()):
            raise ValidationError('Student does not meet the prerequisites for this course')
        registration = self.create(student=student, course=course)
        return registration

class StudentRegistration(models.Model):
    student = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True, related_name='registrations')
    completed = models.BooleanField(default=False)

    objects = StudentRegistrationManager()

    def __str__(self):
        student_name = self.student.user.username if self.student and self.student.user else "Unknown student"
        course_code = self.course.code if self.course else "Unknown course"
        return f"{student_name} - {course_code}"

    class Meta:
        unique_together = ('student', 'course')

class Notification(models.Model):
    message = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    deadline_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Notification created on {self.date_created.strftime('%Y-%m-%d')} - Active: {self.active}"

courses/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .models import *
from .forms import *
from django.contrib.auth.models import User, Group
from .decorators import *
from django.views.decorators.cache import cache_control
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse


@allowed_users(allowed_roles=['admin'])
def save_selected_students(request):
    if request.method == 'POST':
        selected_student_ids = request.POST.getlist('student_ids[]')
        request.session['selected_student_ids'] = selected_student_ids

        
        courses = Course.objects.filter(students__id__in=selected_student_ids).distinct()

       
        course_data = []
        for course in courses:
            course_data.append({
                'code': course.code,
                'name': course.name,
                'prerequisites': ", ".join([prerequisite.name for prerequisite in course.prerequisites.all()]),
                'instructor': course.instructor,
                'completed': course.completed
            })

        return JsonResponse({'status': 'success', 'courses': course_data})
    return JsonResponse({'status': 'fail'})

@login_required(login_url="login")
@allowed_users(allowed_roles=['admin'])
def update_course(request, course_code):
    course = get_object_or_404(Course, code=course_code)
    schedules = CourseSchedule.objects.all()
    prerequisites = Course.objects.exclude(code=course_code)  # Exclude current course from prerequisites

    if request.method == 'POST':
        form = CourseUpdateForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            messages.success(request, f"Course {course.name} has been updated successfully.")
            return redirect('course_list')
    else:
        form = CourseUpdateForm(instance=course)

    context = {
        'course': course,
        'form': form,
        'schedules': schedules,
        'prerequisites': prerequisites,
    }

    return render(request, 'courses/Admin/update_course.html', context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['admin'])
def student_registration(request):
    if request.method == 'POST':
        student_ids = request.POST.getlist('student_id')
        course_codes = request.POST.getlist('course_code')
        for student_id in student_ids:
            student = get_object_or_404(Student, id=student_id)
            for course_code in course_codes:
                course = get_object_or_404(Course, code=course_code)
                try:
                    StudentRegistration.objects.create(student=student, course=course)
                    messages.success(request, f"Successfully registered {student.user.username} for course {course.name}")
                except ValidationError as e:
                    messages.error(request, str(e))
        return redirect('student_registration')
    else:
        students = Student.objects.all()
        courses = Course.objects.all()

        selected_students = request.session.get('selected_students', [])
        if selected_students:
            courses = courses.filter(students__id__in=selected_students).distinct()

        context = {
            'students': students,
            'courses': courses,
        }
        return render(request, 'courses/Admin/student_registration.html', context)
@login_required(login_url="login")
@student_required

def courses(request):
    query = request.GET.get('search_query', '')
    student = None
    registered_courses = set()
    completed_courses = []

    if 'student_id' in request.session:
        student = Student.objects.get(id=request.session['student_id'])
        registered_courses = set(StudentRegistration.objects.filter(student=student).values_list('course__code', flat=True))
        completed_courses = StudentRegistration.objects.filter(student=student, completed=True)
        completed_courses_codes = [registration.course.code for registration in completed_courses]
    else:
        completed_courses_codes = []

    courses = Course.objects.filter(
        Q(code__icontains=query) | 
        Q(name__icontains=query)
    ).exclude(code__in=completed_courses_codes)

    course_data = []
    for course in courses:
        prerequisites_met = all(StudentRegistration.objects.filter(student=student, course=prerequisite).exists() for prerequisite in course.prerequisites.all())
        if prerequisites_met:
            registered_students_count = StudentRegistration.objects.filter(course=course).count()
            available_spots = course.capacity - registered_students_count
            course_data.append({
                'course': course,
                'available_spots': available_spots,
                'registered_students_count': registered_students_count,
                'is_registered': course.code in registered_courses,
            })

    context = {
        'student': student,
        'course_data': course_data,
        'query': query,
        'username': request.user.username,
        'completed_courses': completed_courses
    }
    return render(request, "courses/Student/courses.html", context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def logout_view(request):
    logout(request)
    request.session.flush()
    return redirect('login')

@login_required(login_url="login")
@allowed_users(allowed_roles=['admin'])
def course_report(request):
    courses = Course.objects.all()
    report_data = []

    for course in courses:
        enrollment_count = StudentRegistration.objects.filter(course=course).count()
        popularity = (enrollment_count / course.capacity) * 100 if course.capacity > 0 else 0
        report_data.append({
            'course': course,
            'enrollment_count': enrollment_count,
            'popularity': popularity
        })

    report_data.sort(key=lambda x: x['enrollment_count'], reverse=True)

    most_popular_course = report_data[0] if report_data else None
    least_popular_course = report_data[-1] if report_data else None

    context = {
        'report_data': report_data,
        'most_popular_course': most_popular_course,
        'least_popular_course': least_popular_course
    }
    return render(request, 'courses/Admin/course_report.html', context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['admin'])
def delete_course(request, course_code):
    course = get_object_or_404(Course, code=course_code)
    course.delete()
    messages.success(request, f"Course {course.name} has been successfully deleted.")
    return redirect('course_list')

@login_required(login_url="login")
@student_required
def register_course(request, course_code):
    if 'student_id' not in request.session:
        raise PermissionDenied
    
    student = get_object_or_404(Student, id=request.session['student_id'])
    course = get_object_or_404(Course, code=course_code)

    if StudentRegistration.objects.filter(student=student, course=course).exists():
        messages.error(request, "You are already registered for this course.")
        return redirect('courses')

    student_courses = StudentRegistration.objects.filter(student=student)
    for registration in student_courses:
        if registration.course:
            registered_schedule = registration.course.scheduled
            new_schedule = course.scheduled
            if registered_schedule.days == new_schedule.days and (
                (registered_schedule.start_time <= new_schedule.start_time < registered_schedule.end_time) or 
                (registered_schedule.start_time < new_schedule.end_time <= registered_schedule.end_time)
            ):
                messages.error(request, f"Schedule conflict detected with course {registration.course.code}.")
                return redirect('courses')

    for prerequisite in course.prerequisites.all():
        if not StudentRegistration.objects.filter(student=student, course=prerequisite).exists():
            messages.error(request, f"You do not meet the prerequisites for this course: {prerequisite.name}.")
            return redirect('courses')

    if course.capacity <= StudentRegistration.objects.filter(course=course).count():
        messages.error(request, "This course is already full.")
        return redirect('courses')

    StudentRegistration.objects.create(student=student, course=course)
    messages.success(request, "You have successfully registered for the course.")
    return redirect('courses')

@login_required(login_url="login")
@student_required
def profile(request):
    student = get_object_or_404(Student, id=request.session['student_id'])
    user = student.user

    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            if form.cleaned_data['password1']:
                user.set_password(form.cleaned_data['password1'])
            user.save()
            login(request, user)
            messages.success(request, "Profile updated successfully.")
            return redirect('profile')
        else:
            for error in form.errors.values():
                messages.error(request, error)
    else:
        form = UserUpdateForm(instance=user)
    
    context = {
        'student': student,
        'form': form
    }
    return render(request, 'courses/Student/profile.html', context)

@login_required(login_url="login")
@student_required
def home(request):
    if request.user.is_superuser:
        return redirect('homeAdmin')

    notifications = Notification.objects.filter(active=True).order_by('-date_created')

    context = {
        'notifications': notifications,
        'username': request.user.username,
    }

courses/templates/courses/Admin/addSchedule.html
{% extends "courses/Admin/mainadmin.html" %}

{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% block content %}
    <h2 style="margin-top: 20px; margin-left: 10px;">Add New Schedule</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="margin-bottom: 20px; margin-left: 10px;">Add Schedule</button>
    </form>
    <a href="{% url 'schedule_list' %}" style= " margin-left: 10px;">Back to Schedule List</a>
    {% endblock content %}

courses/templates/courses/Admin/addcourses.html
{% extends "courses/Admin/mainadmin.html" %}

{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% block content %}
    <h2 style="margin-top : 20px">Add Course</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="margin-bottom: 20px;">Add Course</button>
    </form>
    <a href="{% url 'course_list' %}" style="padding-bottom: 20px;">Back to Course List</a>

{%endblock content%}

courses/templates/courses/Admin/course_report.html
{% extends "courses/Admin/mainadmin.html" %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% load static %}
{% block content %}
<h2 style="margin-top: 20px; margin-left: 10px;">Course Enrollment Report</h2>
<table class="table">
    <thead>
        <tr>
            <th>Course Code</th>
            <th>Course Name</th>
            <th>Instructor</th>
            <th>Enrollment Count</th>
            <th>Capacity</th>
            <th>Popularity (%)</th>
        </tr>
    </thead>
    <tbody>
        {% for data in report_data %}
        <tr>
            <td>{{ data.course.code }}</td>
            <td>{{ data.course.name }}</td>
            <td>{{ data.course.instructor }}</td>
            <td>{{ data.enrollment_count }}</td>
            <td>{{ data.course.capacity }}</td>
            <td>{{ data.popularity|floatformat:2 }}%</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h2 style="margin-top: 20px; margin-left: 10px;">Analytics</h2>
{% if most_popular_course %}
    <p style="margin-left: 10px;"><strong>Most Popular Course:</strong> {{ most_popular_course.course.name }} ({{ most_popular_course.enrollment_count }} enrollments)</p>
{% endif %}
{% if least_popular_course %}
    <p style="margin-left: 10px;"><strong>Least Popular Course:</strong> {{ least_popular_course.course.name }} ({{ least_popular_course.enrollment_count }} enrollments)</p>
{% endif %}
{% endblock %}

courses/templates/courses/Admin/courses_list.html
{% extends "courses/Admin/mainadmin.html" %}
{% load static %}
<link  rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% block content %}
    <h2 style="margin-top: 20px">Course List</h2>
    <table class="table table-bordered mt-5 text-center border-primary text-capitalize">
        <thead>
            <tr>
                <th>Course Code</th>
                <th>Course Name</th>
                <th>Description</th>
                <th>Instructor</th>
                <th>Schedule</th>
                <th>Prerequisites</th>
                <th>Capacity</th>

            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.code }}</td>
                    <td>{{ course.name }}</td>
                    <td>{{ course.description }}</td>
                    <td>{{ course.instructor }}</td>
                    <td>
                        {% if course.scheduled %}
                            {{ course.scheduled.days }}: {{ course.scheduled.start_time|date:"g:i A" }} - {{ course.scheduled.end_time|date:"g:i A" }} (Room: {{ course.scheduled.room_no }})
                        {% else %}
                            No Schedule
                        {% endif %}
                    </td>
                    <td>
                        {% if course.prerequisites.exists %}
                            {{ course.prerequisites.all|join:", " }}
                        {% else %}
                            None
                        {% endif %}
                    </td>
                    <td>{{ course.capacity }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'add_course' %}">Add New Course</a>
    <br>
    <a href="{% url 'removeeditcourse' %}">Remove or Edit Course</a>


{% endblock content %}

courses/templates/courses/Admin/homeAdmin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course Registration System | Home</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    
    <link rel="stylesheet" href={% static "css//index.css" %}>

</head>

<body>
    <header>
        <nav>
            <div class="nav-content Content">
                <div class="ul-content">
                    <div class="mb-3">
                        <a href="{% url 'homeAdmin' %}">
                            <img src="{% static 'imgs/logo.png' %}" width="60px" style="no-repeat" alt="logo">
                        </a>
                    </div>
                    <ul>
                        <li><a href="{% url 'homeAdmin' %}" style="color: #00008b; text-decoration: none;">Home</a></li>
                        <li><a href="{% url 'student_course_list' %}" style="color: #00008b; text-decoration: none;">Students</a></li>
                        <li><a href="{% url 'course_list' %}" style="color:#00008b;text-decoration: none;">Courses</a></li>
                        <li><a href="{% url 'schedule_list' %}" style="color:#00008b;text-decoration: none;">Scheduler</a></li>
                        <li><a href="{% url 'student_registration' %}" style="color:#00008b;text-decoration: none;">Register</a></li>
                        <li><a href="{% url 'course_report' %}" style="color: #00008b; text-decoration: none;">Report</a></li>
                            </ul>
                </div>
                <div class="logout">
                    <select name="" style="background: none;" id="pageSelect" onchange="location = this.value;">
                        <option>{{ username }}</option>
                        <option value="{% url 'logout' %}" class="btn btn-danger">Logout</option>
                    </select>
                </div>
           

        </nav>
        {% for notification in notifications.message %}
        <div class="alert alert-info" role="alert">
            {{ notification.message }}
            {% if notification.deadline_date %}
            {% endif %}
        </div>
        {% endfor %}
    
        
        <div class="row container d-flex align-items-center justify-content-center mt-5 text-capitalize">
            <img src="{% static 'imgs/logo.png' %}"  width= "80px"  class="logo col-md-3 mt-5 m-5" alt="logo">
            <h1 class="col-md-8 mt-5">Welcome to Admin Registration System Website</h1>
        </div>
    </header>
    

    <script>
        document.getElementById('pageSelect').addEventListener('change', function () {
            const selectedPage = this.value;
            if (selectedPage) {
                window.location.href = selectedPage;
            }
        });
    </script>
</body>

</html>

courses/templates/courses/Admin/mainadmin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course Registration System | Admin</title>
</head>
<body>

    {% include "courses/Admin/navgibaradmin.html" %}
    {% block content %}
    {% endblock content %}

</body>
</html>

courses/templates/courses/Admin/navgibaradmin.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">


  <nav>
    <div class="nav-content Content">
        <div class="ul-content">
            <div class="mb-3">
                <a href="{% url 'homeAdmin' %}">
                    <img src="{% static 'imgs/logo.png' %}" width="60px" alt="logo">                </a>
            </div>
            <ul>
                <li><a href="{% url 'homeAdmin' %}" style="color: #00008b; text-decoration: none;">Home</a></li>
                <li><a href="{% url 'student_course_list' %}" style="color: #00008b; text-decoration: none;">Students</a></li>
                <li><a href="{% url 'course_list' %}" style="color:#00008b;text-decoration: none;">Courses</a></li>
                <li><a href="{% url 'schedule_list' %}" style="color:#00008b;text-decoration: none;">Scheduler</a></li>
                <li><a href="{% url 'student_registration' %}" style="color:#00008b;text-decoration: none;">Register</a></li>
                <li><a href="{% url 'course_report' %}" style="color: #00008b; text-decoration: none;">Report</a></li>

            </ul>
        </div>
        <div class="logout">
            <select name="" style="background: none;" id="pageSelect" onchange="location = this.value;">
                <option>{{ request.user.username }}</option>
                <option value="{% url 'logout' %}" class="btn btn-danger">Logout</option>
            </select>
        </div>
    </div>
</nav>

courses/templates/courses/Admin/remove&editcourse.html
{% extends "courses/Admin/mainadmin.html" %}
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% block content %}
    <h2 style="margin-top : 20px">Remove Or Edit Course</h2>
    <table class="table table-bordered mt-5 text-center border-primary text-capitalize">
        <thead>
            <tr>
                <th>Course Code</th>
                <th>Course Name</th>
                <th>Description</th>
                <th>Instructor</th>
                <th>Schedule</th>
                <th>Prerequisites</th>
                <th>Capacity</th>
                <th>Action</th> 
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.code }}</td>
                    <td>{{ course.name }}</td>
                    <td>{{ course.description }}</td>
                    <td>{{ course.instructor }}</td>
                    <td>
                        {% if course.scheduled %}
                            {{ course.scheduled.days }}: {{ course.scheduled.start_time|date:"g:i A" }} - {{ course.scheduled.end_time|date:"g:i A" }} (Room: {{ course.scheduled.room_no }})
                        {% else %}
                            No Schedule
                        {% endif %}
                    </td>
                    <td>
                        {% if course.prerequisites.exists %}
                            {{ course.prerequisites.all|join:", " }}
                        {% else %}
                            None
                        {% endif %}
                    </td>
                    <td>{{ course.capacity }}</td>
                    <td>
                        <form action="{% url 'update_course' course.code %}" method="get" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                        <form action="{% url 'delete_course' course.code %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'course_list' %}" style="padding-bottom: 20px;">Back to Course List</a>
{% endblock content %}

courses/templates/courses/Admin/schedule_list.html
{% extends "courses/Admin/mainadmin.html" %}

{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block content %}
    <h1>Schedule List</h1>
    
        <table class="table table-bordered mt-5 text-center border-primary text-capitalize">

        <thead>
            <tr>
                <th>Days</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Room Number</th>
            </tr>
        </thead>
        <tbody>
            {% for schedule in schedules %}
                <tr>
                    <td>{{ schedule.days }}</td>
                    <td>{{ schedule.start_time }}</td>
                    <td>{{ schedule.end_time }}</td>
                    <td>{{ schedule.room_no }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'add_schedule' %}">Add New Schedule</a>
    {% endblock content %}

courses/templates/courses/Admin/student_course_list.html
{% extends "courses/Admin/mainadmin.html" %}

{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% block content %}


<h2 style="margin-top: 20px; margin-left: 10px;">Student Course List</h2>

<h4 style="margin-left: 10px;">Add New Student</h4>
<form method="POST" action="">
    {% csrf_token %}
    <div class="mb-3">
        <label style=" margin-left: 10px;" for="{{ form.username.id_for_label }}" class="form-label">Username</label>
        {{ form.username }}
        {{ form.username.errors }}
    </div>
    <div class="mb-3">
        <label style=" margin-left: 10px;" for="{{ form.email.id_for_label }}" class="form-label">Email</label>
        {{ form.email }}
        {{ form.email.errors }}
    </div>
    <div class="mb-3">
        <label style=" margin-left: 10px;" for="{{ form.password.id_for_label }}" class="form-label">Password</label>
        {{ form.password }}
        {{ form.password.errors }}
    </div>
    <button style=" margin-left: 10px; margin-bottom: 20px;" type="submit" class="btn btn-primary">Add Student</button>
</form>

<h2>Existing Students</h2>
<table class="table">

    <thead>
        <tr>
            <th>Username</th>
            <th>Courses Registered</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.user.username }}</td>
                <td>
                    <ul>
                        {% for registration in student.studentregistration_set.all %}
                            <li>{{ registration.course.name }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}